# Generated by Django 4.1.7 on 2023-03-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyData',
            new_name='Dropdown',
        ),
        migrations.RenameField(
            model_name='dropdown',
            old_name='playlist_id',
            new_name='user_input',
        ),
    ]
