# Generated by Django 4.1.7 on 2023-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_rename_mydata_dropdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Dropdown',
        ),
    ]
